AWSTemplateFormatVersion: "2010-09-09"
Description: "Create RDS MySQL"
Resources:
  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: "8.0.32"
      MasterUsername: admin
      MasterUserPassword: admin123
      AllocatedStorage: 20
      DBInstanceIdentifier: dbspringbootlocalstack
      DBName: dbspringbootlocalstack
      MultiAZ: false
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroup

  DBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: seg-db-spring-boot-localstack
      GroupDescription: "Security group for RDS MySQL database"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup
